version: "3"

services:
  rabbit_mq:
    image: rabbitmq:3.8.3-management
    container_name: rabbit_mq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/